name: null.fs tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        # uses: dtolnay/rust-toolchain@1.81.0

      - name: Run tests
        run: cargo test --verbose
